#! /bin/sh

pkill sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

pkill feh
feh --bg-fill $HOME/.local/share/background/city.jpg &

pgrep -x numlockx > /dev/null || numlockx on &

pkill picom
picom --experimental-backends &

pkill polybar
polybar top -c $HOME/.config/polybar/config.ini &


bspc monitor -d I II III IV V 

bspc config border_width        1.5
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0
bspc config bottom_padding 20
bspc config right_padding 0
bspc config left_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "$color1"
