#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x feh > /dev/null || feh --bg-fill $HOME/.local/share/background/wall-01.png &
pgrep -x numlockx > /dev/null || numlockx on &
pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x polybar > /dev/null || polybar top -c $HOME/.config/polybar/config.ini &


bspc monitor -d I II III IV V 

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 17
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

bspc config focused_border_color     "#ffffff"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
